# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
import random


class Ui_Dialog(object):
    def __init__(self):
        self.names = "张吉惟、林国瑞、林玟书、林雅南、江奕云、刘柏宏、阮建安、林子帆、夏志豪、吉茹定、李中冰、黄文隆、谢彦文、傅智翔、洪振霞、刘姿婷、荣姿康、吕致盈、方一强、黎芸贵、郑伊雯、雷进宝、吴美隆、吴心真、王美珠、郭芳天、李雅惠、陈文婷、曹敏侑、王依婷、陈婉璇、吴美玉、蔡依婷、郑昌梦、林家纶、黄丽昆、李育泉、黄芸欢、吴韵如、李肇芬、卢木仲、李成白、方兆玉、刘翊惠、丁汉臻、吴佳瑞、舒绿珮、周白芷、张姿妤、张虹伦、周琼玟、倪怡芳、郭贵妃、杨佩芳、黄文旺 "
        self.n_list = self.names.split("、")
        self.noroll_call = self.n_list.copy()  # 未点名点名
        self.roll_call = []

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 500)
        self.pushButton_name = QtWidgets.QPushButton(Dialog)
        self.pushButton_name.setGeometry(QtCore.QRect(180, 250, 141, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_name.setFont(font)
        self.pushButton_name.setObjectName("pushButton_name")
        self.pushButton_name.clicked.connect(self.onClick)
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setGeometry(QtCore.QRect(30, 100, 431, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(35)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_name.setText(_translate("Dialog", "点名"))
        self.label_name.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">请点名</p></body></html>"))

    def onClick(self):
        if not self.noroll_call:  # 当未点名列表为空时，将未点名列表和已点名列表互换
            self.noroll_call, self.roll_call = self.roll_call, self.noroll_call
        name = random.choice(self.noroll_call)
        self.noroll_call.remove(name)
        self.roll_call.append(name)
        self.label_name.setText(name)


class MyWindow(QMainWindow, Ui_Dialog):
    def __init__(self, parent=None):
        super(MyWindow, self).__init__(parent)
        self.setupUi(self)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    myWin = MyWindow()
    myWin.show()
    sys.exit(app.exec_())
